fixed con - when no country code is supplied

diff --git a/scripts/con b/scripts/con
--- a/scripts/con
+++ b/scripts/con
@@ -3,6 +3,11 @@
 country_code=$1
 with_replica=$2
 
+if [ "$country_code" = "" ]; then
+    echo "[Error] No country code supplied"
+    exit 1
+fi
+
 
 function connect {
     script_path='~'
